// Generated by tools/sync_version.py. Do not edit manually.
#pragma once

#define COOPANDREAS_VERSION "0.2.18"
#define COOPANDREAS_VERSION_MAJOR 0
#define COOPANDREAS_VERSION_MINOR 2
#define COOPANDREAS_VERSION_PATCH 18
#define COOPANDREAS_VERSION_STAGE "release"
#define COOPANDREAS_VERSION_FILE 0,2,18,0
