#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
VERSION_FILE = ROOT / "version.json"
SHARED_HEADER = ROOT / "shared" / "version.h"
CLIENT_RC = ROOT / "client" / "version.rc"
SERVER_RC = ROOT / "server" / "version.rc"


def load_version() -> dict[str, object]:
    with VERSION_FILE.open("r", encoding="utf-8") as handle:
        data = json.load(handle)

    stage = str(data.get("stage", "release"))
    if stage not in {"release", "alpha", "beta"}:
        raise ValueError(f"Unsupported stage: {stage}")

    return {
        "major": int(data["major"]),
        "minor": int(data["minor"]),
        "patch": int(data["patch"]),
        "stage": stage,
    }


def save_version(version: dict[str, object]) -> None:
    VERSION_FILE.write_text(
        json.dumps(version, indent=2) + "\n",
        encoding="utf-8",
    )


def version_string(version: dict[str, object]) -> str:
    base = f'{version["major"]}.{version["minor"]}.{version["patch"]}'
    return base if version["stage"] == "release" else f'{base}-{version["stage"]}'


def rc_tuple(version: dict[str, object]) -> str:
    return f'{version["major"]},{version["minor"]},{version["patch"]},0'


def render_shared_header(version: dict[str, object]) -> str:
    return (
        "// Generated by tools/sync_version.py. Do not edit manually.\n"
        "#pragma once\n"
        "\n"
        '#define COOPANDREAS_VERSION "{}"\n'
        "#define COOPANDREAS_VERSION_MAJOR {}\n"
        "#define COOPANDREAS_VERSION_MINOR {}\n"
        "#define COOPANDREAS_VERSION_PATCH {}\n"
        '#define COOPANDREAS_VERSION_STAGE "{}"\n'
        "#define COOPANDREAS_VERSION_FILE {},0\n"
    ).format(
        version_string(version),
        version["major"],
        version["minor"],
        version["patch"],
        version["stage"],
        f'{version["major"]},{version["minor"]},{version["patch"]}',
    )


def update_file(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def rewrite_client_rc(version: dict[str, object]) -> None:
    content = CLIENT_RC.read_text(encoding="utf-8")
    content = re.sub(r"FILEVERSION\s+\d+,\d+,\d+,\d+", f"FILEVERSION {rc_tuple(version)}", content)
    content = re.sub(r"PRODUCTVERSION\s+\d+,\d+,\d+,\d+", f"PRODUCTVERSION {rc_tuple(version)}", content)
    content = re.sub(r'VALUE "FileVersion", "[^"]+"', f'VALUE "FileVersion", "{version_string(version)}"', content)
    content = re.sub(r'VALUE "ProductVersion", "[^"]+"', f'VALUE "ProductVersion", "{version_string(version)}"', content)
    update_file(CLIENT_RC, content)


def rewrite_server_rc(version: dict[str, object]) -> None:
    content = SERVER_RC.read_text(encoding="utf-8")
    content = re.sub(r"FILEVERSION\s+\d+,\s*\d+,\s*\d+", f'FILEVERSION {version["major"]}, {version["minor"]}, {version["patch"]}', content)
    content = re.sub(r"PRODUCTVERSION\s+\d+,\s*\d+,\s*\d+", f'PRODUCTVERSION {version["major"]}, {version["minor"]}, {version["patch"]}', content)
    content = re.sub(r'VALUE "FileVersion", "[^"]+"', f'VALUE "FileVersion", "{version_string(version)}"', content)
    content = re.sub(r'VALUE "ProductVersion", "[^"]+"', f'VALUE "ProductVersion", "{version_string(version)}"', content)
    update_file(SERVER_RC, content)


def render_client_rc(version: dict[str, object]) -> str:
    content = CLIENT_RC.read_text(encoding="utf-8")
    content = re.sub(r"FILEVERSION\s+\d+,\d+,\d+,\d+", f"FILEVERSION {rc_tuple(version)}", content)
    content = re.sub(r"PRODUCTVERSION\s+\d+,\d+,\d+,\d+", f"PRODUCTVERSION {rc_tuple(version)}", content)
    content = re.sub(r'VALUE "FileVersion", "[^"]+"', f'VALUE "FileVersion", "{version_string(version)}"', content)
    content = re.sub(r'VALUE "ProductVersion", "[^"]+"', f'VALUE "ProductVersion", "{version_string(version)}"', content)
    return content


def render_server_rc(version: dict[str, object]) -> str:
    content = SERVER_RC.read_text(encoding="utf-8")
    content = re.sub(r"FILEVERSION\s+\d+,\s*\d+,\s*\d+", f'FILEVERSION {version["major"]}, {version["minor"]}, {version["patch"]}', content)
    content = re.sub(r"PRODUCTVERSION\s+\d+,\s*\d+,\s*\d+", f'PRODUCTVERSION {version["major"]}, {version["minor"]}, {version["patch"]}', content)
    content = re.sub(r'VALUE "FileVersion", "[^"]+"', f'VALUE "FileVersion", "{version_string(version)}"', content)
    content = re.sub(r'VALUE "ProductVersion", "[^"]+"', f'VALUE "ProductVersion", "{version_string(version)}"', content)
    return content


def sync(version: dict[str, object]) -> None:
    update_file(SHARED_HEADER, render_shared_header(version))
    update_file(CLIENT_RC, render_client_rc(version))
    update_file(SERVER_RC, render_server_rc(version))


def bump(version: dict[str, object], part: str) -> dict[str, object]:
    if part == "major":
        version["major"] = int(version["major"]) + 1
        version["minor"] = 0
        version["patch"] = 0
    elif part == "minor":
        version["minor"] = int(version["minor"]) + 1
        version["patch"] = 0
    elif part == "patch":
        version["patch"] = int(version["patch"]) + 1
    else:
        raise ValueError(f"Unsupported bump part: {part}")
    return version


def main() -> int:
    parser = argparse.ArgumentParser(description="Synchronize CoopAndreas version files.")
    parser.add_argument("--bump", choices=["major", "minor", "patch"])
    parser.add_argument("--print", action="store_true", dest="print_version")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    version = load_version()
    if args.bump:
        version = bump(version, args.bump)
        save_version(version)

    expected_header = render_shared_header(version)
    expected_client_rc = render_client_rc(version)
    expected_server_rc = render_server_rc(version)

    if not args.check:
        sync(version)

    if args.print_version:
        print(version_string(version))

    if args.check:
        issues: list[str] = []
        if SHARED_HEADER.read_text(encoding="utf-8") != expected_header:
            issues.append(str(SHARED_HEADER.relative_to(ROOT)))
        if CLIENT_RC.read_text(encoding="utf-8") != expected_client_rc:
            issues.append(str(CLIENT_RC.relative_to(ROOT)))
        if SERVER_RC.read_text(encoding="utf-8") != expected_server_rc:
            issues.append(str(SERVER_RC.relative_to(ROOT)))
        if issues:
            raise SystemExit(f"Version sync check failed for: {', '.join(issues)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
